services:
  db:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    container_name: shopperdb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - shopper
    ports:
      - 27017:27017
  app:
    build: .
    container_name: shopperapp
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - db
networks:
  shopper:
    driver: bridge
volumes:
  mongodb-data:
